### ISSUE TITLE
proto

### ISSUE THREAD

**Issue by 89z** [NoahMauthe/APIs#1]
where did this file come from:

https://github.com/NoahMauthe/APIs/blob/master/API/resources/GooglePlayAPI.proto

**Comment by NoahMauthe** [comment]
As mentioned in the readme, the API was originally inspired by [NoMore201's googleplay API](https://github.com/NoMore201/googleplay-api/blob/master/googleplay.proto) which is where original version of the file is from. We modified it for our own purposes.
